# Generated by Django 4.2.16 on 2024-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='monedero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
